{{- if .Values.worker.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-worker
  labels:
    app: worker
spec:
  replicas: {{ .Values.worker.replicas }}
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      serviceAccountName: {{ .Release.Name }}-{{ .Values.serviceAccount.name }}
      containers:
        - name: worker
          image: {{ .Values.worker.image }}
          resources:
{{ toYaml .Values.worker.resources | indent 12 }}
          env:
          {{- if .Values.secret.enabled }}
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-voting-app
                  key: DB_HOST
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-voting-app
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-voting-app
                  key: DB_PASSWORD
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-voting-app
                  key: REDIS_HOST
          {{- end }}

      {{- if .Values.worker.tolerations }}
      tolerations:
{{ toYaml .Values.worker.tolerations | indent 8 }}
      {{- end }}
        
      {{- if .Values.worker.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.worker.nodeSelector | indent 8 }}
      {{- end }}

      {{- if .Values.worker.affinity }}
      affinity:
{{ toYaml .Values.worker.affinity | indent 8 }}
      {{- end }}
{{- end -}}
