{{- if .Values.vote.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-vote
  labels:
    app: vote-app
spec:
  replicas: {{ .Values.vote.replicas }}
  selector:
    matchLabels:
      app: vote-app
  template:
    metadata:
      labels:
        app: vote-app
    spec:
      serviceAccountName: {{ .Release.Name }}-{{ .Values.serviceAccount.name }}
      containers:
        - name: vote-app
          image: {{ .Values.vote.image }}
          ports:
            - containerPort: 5000
          resources:
{{ toYaml .Values.vote.resources | indent 12 }}
          env:
          {{- if .Values.secret.enabled }}
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-voting-app
                  key: REDIS_HOST
          {{- end }}

      {{- if .Values.vote.tolerations }}
      tolerations:
{{ toYaml .Values.vote.tolerations | indent 8 }}
      {{- end }}
        
      {{- if .Values.vote.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.vote.nodeSelector | indent 8 }}
      {{- end }}

      {{- if .Values.vote.affinity }}
      affinity:
{{ toYaml .Values.vote.affinity | indent 8 }}
      {{- end }}
{{- end -}}
