{{- if and .Values.ingress.enabled .Values.ingress.tlsEnabled (ne .Values.ingress.hostname "") -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-voting-app
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  tls:
    - hosts:
        - {{ .Values.ingress.hostname }}
      secretName: {{ .Values.ingress.hostname }}-tls-secret
  rules:
    - host: {{ .Values.ingress.hostname }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-vote
                port:
                  number: 80
          - path: /results
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-result
                port:
                  number: 80
{{- else -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-voting-app
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-vote
                port:
                  number: 80
          - path: /results
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-result
                port:
                  number: 80
{{- end -}}
