{{- if .Values.secret.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-voting-app
type: Opaque
data:
  DB_USERNAME: {{ .Values.secret.data.dbUsername | b64enc | quote }}
  DB_PASSWORD: {{ .Values.secret.data.dbPassword | b64enc | quote }}
  DB_HOST: {{ printf "%s-postgresql" .Release.Name | b64enc | quote }}
  REDIS_HOST: {{ printf "%s-redis-master" .Release.Name | b64enc | quote }}
{{- end -}}