{{- if .Values.result.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-result
spec:
  selector:
    app: result-app
  type: {{ .Values.result.service.type }}
  ports:
    - port: {{ .Values.result.service.port }}
      targetPort: {{ .Values.result.service.targetPort }}
      {{- if eq .Values.result.service.type "NodePort" }}
      nodePort: {{ .Values.result.service.nodePort | default "" }}
      {{- end }}
{{- end -}}