{{- if .Values.vote.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-vote
spec:
  selector:
    app: vote-app
  type: {{ .Values.vote.service.type }}
  ports:
    - port: {{ .Values.vote.service.port }}
      targetPort: {{ .Values.vote.service.targetPort }}
      {{- if eq .Values.vote.service.type "NodePort" }}
      nodePort: {{ .Values.vote.service.nodePort | default "" }}
      {{- end }}
{{- end -}}