{{- if .Values.result.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-result
spec:
  type: NodePort
  selector:
    app: result-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5001
{{- end -}}