{{- if .Values.vote.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-vote
spec:
  type: NodePort
  selector:
    app: vote-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
{{- end -}}